version: '3.9'

networks:
  panel_net:

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: '${APP_NAME}-server'
    restart: always
    environment:
      - SERVER_NAME=${SERVER_NAME}
    entrypoint: /usr/local/bin/entrypoint.sh
    logging:
       driver: "local"
       options:
          max-size: "20m"
          max-file: "3"
    ports:
      - 80:80
      - 443:443
      - 8282:8282
    working_dir: /home/panel/public_html
    volumes:
      - /home/panel:/home/panel
      - ./docker/server/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./docker/server/apache/mods-enabled/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/apache/cert:/etc/apache2/cert
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini         
    depends_on:
      memcached:
        condition: service_started
    healthcheck:
      test: curl --fail --insecure https://localhost:443 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - panel_net    
  db_server:
    image: mariadb:10.5.9
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
      - /home/panel/mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - panel_net


  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: '${APP_NAME}-db-admin'
    ports:
      - '${APP_DB_ADMIN_PORT}:80'
    environment:
      PMA_HOST: db_server
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - panel_net
      
  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - 11211:11211
    networks:
      - panel_net
    
  logrotate:
    image: blacklabelops/logrotate 
    container_name: logrotate
    volumes: 
      - /home/panel/logs:/home/panel/logs 
    environment: 
      - LOGS_DIRECTORIES=/home/panel/logs 
      - LOGROTATE_INTERVAL=daily 
      - LOGROTATE_COPIES=2 
      - LOGROTATE_SIZE=25M 
      - LOGROTATE_COMPRESSION=compress
